### ISSUE TITLE
Support YouTube start time

### ISSUE THREAD

**Issue by NomarCub** [samwarnick/obsidian-simple-embeds#12]
Normal YouTube links can have a `?start=`, `&t=`, `?t=` suffix that should be preserved (and in case of the latter two, turned into `?start=`, which is the only one embed accepts).

**Comment by NomarCub** [comment]
The `&` way also allows specifying hours and minutes like so: `&t=1h6m47s`. It would be nice if the plugin converted this (to seconds), rather than passing it on to the iframe, which can't handle it as is.

**Comment by samwarnick** [comment]
Thanks, wasn't aware of the other format. I'll get that added as well.
