### ISSUE TITLE
Can you embed twitter thread into obsidian 

### ISSUE THREAD

**Issue by skillhacker-code** [samwarnick/obsidian-simple-embeds#15]
When i copied twitter thread it is only showing the first tweet only , is there any way to embed the compleated twitter thread

**Comment by samwarnick** [comment]
Unfortunately the Twitter embed API does not have a way of embedding an entire thread. An embed will show the previous tweet though if it's replying to a tweet.

https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview
