### ISSUE TITLE
Integrate with lite-youtube-embed

### ISSUE THREAD

**Issue by xplosionmind** [samwarnick/obsidian-simple-embeds#34]
[`lite-youtube-embed`](https://github.com/paulirish/lite-youtube-embed 'lite-youtube-embed on GitHub') is an awesome npm package that makes YouTube embeds *way* faster and more privacy respectful.

It would be lovely if the embed generated by this plugin could be generated with it.

**Comment by samwarnick** [comment]
I've been meaning to look into this for a while now. I'll try to get to it soon. Thanks for bringing it up.

**Comment by xplosionmind** [comment]
Thank **you**! My pleasure.
