### ISSUE TITLE
iPadOS: Failed to load plugin simple-embed

### ISSUE THREAD

**Issue by KelsoUxlay** [samwarnick/obsidian-simple-embeds#35]
For the last few days, I can no longer use simple embeds on my iPad. Trying to activate the plugin always generates the following message: "Failed to load plugin simple-embeds". It used to work well. Still working well on my PC.

**Comment by samwarnick** [comment]
Thanks for reporting. I'm seeing the same thing. There appears to be an API or syntax that Safari does not like in one of the libraries I'm using. Looking for a workaround now

**Comment by samwarnick** [comment]
@KelsoUxlay should be fixed now in 1.10.2

**Comment by KelsoUxlay** [comment]
Fixed! That was fast! Good work
