### ISSUE TITLE
Feature Request - Add Vimeo link

### ISSUE THREAD

**Issue by adxsoft** [samwarnick/obsidian-simple-embeds#38]
Nice plugin.
Would be great to have Vimeo embed covered in a future release.
Thanks

**Comment by samwarnick** [comment]
Added in [1.11.0](https://github.com/samwarnick/obsidian-simple-embeds/releases/tag/1.11.0). I'm not a big Vimeo user, so let me know if the links you're trying to use don't work.

**Comment by adxsoft** [comment]
Apologies for the late response. The Vimeo option works perfectly. 
Probably a good idea to update the readme to reflect the wide range of options you now have.
Thanks!!
