### ISSUE TITLE
YouTube Shorts Support

### ISSUE THREAD

**Issue by CamronWalker** [samwarnick/obsidian-simple-embeds#41]
I end up finding a lot of good quotes in YouTube Shorts. It would be nice if these links also worked with simple embeds. The embedding works the same it's just the link's regex would be different.

`https://youtube.com/shorts/VIDEOID?feature=share`

It should probably have its own CSS class because most of the videos are in portrait.

**Comment by samwarnick** [comment]
Added in 1.12.0
