### ISSUE TITLE
`Error: [CM6][simple-embeds] Using a deprecated package: "@codemirror/rangeset"`

### ISSUE THREAD

**Issue by NomarCub** [samwarnick/obsidian-simple-embeds#45]
This error message shows on the console on startup.
There's also this link in the details, among other things: https://discuss.codemirror.net/t/release-0-20-0/4302
I have the newest Obsidian Insider version, so it's probably related to their recent CodeMirror migration. They have [this guide](https://forum.obsidian.md/t/plugin-developers-codemirror-6-migration-guide-for-v6-0/38947).

**Comment by YannickTemplay** [comment]
+1

**Comment by lwb52** [comment]
+another

**Comment by fncll** [comment]
Same!

**Comment by NomarCub** [comment]
Please just like the issue if you have no information to contribute. It's annoying to get notifications with no actual content.

**Comment by lwb52** [comment]
that’s all i have: an error message on the developer screen, and it’s alarming to see without context other than that several plugins report the identical error—all w/out further info

-L.W. Brown
via 8s+

**Comment by NomarCub** [comment]
Which other plugins @lwb52? Did you make issues for those? Would you link them here? It'd help track them and could potentially help different developers find a common solution.

**Comment by samwarnick** [comment]
Sorry, been busy. Thanks for reporting. I'll try to figure out an alternative soon.

Or if anyone feels like taking a look, go for it.

**Comment by NomarCub** [comment]
For anyone planning a PR, the guide I linked from the Obsidian devs is probably the best place to start with the CodeMirror changes.
I also found this commit in the official sample plugin, that does the migration there, in a simpler environment: https://github.com/obsidianmd/obsidian-sample-plugin/commit/b46f6c93228713d3dd98c9aa1ad2645c4bb916b0

**Comment by Thylane** [comment]
This error is caused by:
```js
import { RangeSetBuilder } from "@codemirror/rangeset";
```

`RangeSetBuilder` should be imported from `@codemirror/state` in CodeMirror 6.

So the solution is to change `@codemirror/rangeset` to `@codemirror/state`.

**Comment by samwarnick** [comment]
Thanks to @NomarCub for fixing this!
