### ISSUE TITLE
Embeds not rendered in preview mode when "Keep links in preview" is enabled and "Place embeds" is set to "Below link"

### ISSUE THREAD

**Issue by nicolasmarc1** [samwarnick/obsidian-simple-embeds#51]
Hi, just fyi the plugin seems to be broken after obsidian update to v1.
Thanks!

**Comment by NomarCub** [comment]
It works fine for me. Are you on the latest version of the plugin? Could you show the link that doesn't work?

**Comment by nicolasmarc1** [comment]
hmm yeah you right i tried in the sandbox vault and it does work, i'm not sure why it's not rendering on my main vault. I updated all my plugins yesterday so i'm on the last version. None of the links work, here's an example with a youtube and twitter link that is rendered on the sandbox vault but not in my vault

https://user-images.githubusercontent.com/51007222/195983651-cfcaf309-ffbc-4193-bc41-9b16375591d3.mp4

update: 
After turning on the option to show embeds in live preview, it works in live preview, but still doesn't work in preview mode

https://user-images.githubusercontent.com/51007222/195984416-d9385a49-123b-45ea-96f2-f1dc49b997ec.mp4


Any clues on what might cause this? Thanks

**Comment by NomarCub** [comment]
I managed to reproduce it. Only reading view is affected. The embed doesn't show up when I enable `Keep links in preview`  and set `Place embeds` to `Below link`.
```json
{
  "keepLinksInPreview": true,
  "embedPlacement": "below"
}
```

**Comment by nicolasmarc1** [comment]
> I managed to reproduce it. Only reading view is affected. The embed doesn't show up when I enable `Keep links in preview` and set `Place embeds` to `Below link`. Here's the resulting data.json:
> 
> ```json
> {
>   "keepLinksInPreview": true,
>   "embedPlacement": "below"
> }
> ```
> 
> Is it the same for you? Does it happen outside reading view and without keeping links too? Would you rename the issue to reflect these @nicolasmarc1?
Yes thanks, it works now that i disabled Keep links in preview. I've changed the issue

**Comment by beetrootpaul** [comment]
FYI I stumbled upon this bug as well, because my preferred setup is below links

**Comment by samwarnick** [comment]
Thanks everyone for reporting this and especially thanks to @udbhav-s for fixing it! Should get the fix released today.
