### ISSUE TITLE
CodePen support

### ISSUE THREAD

**Issue by samwarnick** [samwarnick/obsidian-simple-embeds#8]

**Comment by kinduff** [comment]
Happy to give this one a shot

**Comment by samwarnick** [comment]
@kinduff Sure! This should be one of the easier ones to add. I hope it's pretty straightforward how it all works, but let me know if you have any questions.

**Comment by samwarnick** [comment]
@kinduff still interested in giving this one a shot? No problem if you no longer want to, just wanted to check before I did it myself.

**Comment by kinduff** [comment]
I'm still interested! Give me this week to find some time :pray:
